### ISSUE TITLE
Support for mixed-radix FFT to exceed 2^15 constraint limit with mnt6753 curve

### ISSUE THREAD

**Issue by PossiblyHarry** [EYBlockchain/zk-swap-libff#5]
As used for the MNT cycle curves by the Coda project rather than using geometric sequence domain for FFT evaluation, see the commit:

 * https://github.com/o1-labs/snarky/commit/3a265b9bf8fd9fdfabc8e5c1b4ef77209a1f556f#diff-beef0da3fea389044d1864bfefc332a4

This will be used for mnt6 (753) because the low 2-adicy limits the number of constraints which can be processed to 2^15:

```
mnt6753_Fr::s = 15;
```

These changes span across libfqfft & libff, currently there is no libfqfft repository in EYblockchain, will have to fork libfqfft and update the reference in libff and libsnark forks.

Need to define additional constants for the curve parameters:

* small_subgroup_defined
* small_subgroup_base
* small_subgroup_power
* full_root_of_unity

full_root_of_unity is generated using:
```
generator^((modulus-1) / (2^s * small_subgroup_base^small_subgroup_power))
```

However, there is no reference or note as to how `small_subgroup_base` and `small_subgroup_power` are decided.

**Comment by PossiblyHarry** [comment]
It seems we can find the small_subgroup_base and small_subgroup_power parameters using the following code:

```python
>>> largest = 0 
... for i in range(1,30): 
...     for j in range(1,20): 
...         for k in range(1,20): 
...             n = (2**i) * (j**k)         
...             res = (r-1) % n          
...             if res == 0: 
...                 if n > largest: 
...                     largest = n                     
...                     chosen = (i,j,k,n) 
...                 print(i, j, k, n, log2(n)) 
... print(log2(largest))    
```

Which gives a candidate `2**13 * (10**2)` which is the same value as `2**15 * (5**2)`

**Comment by ChaitanyaKonda** [comment]
For MNT6753, the small_subgroup_base and small_subgroup_power have been defined in mnt6753_init.cpp in libff as 5 and 2 respectively. Which gives the same number of constraints as the python code above does

**Comment by yelhousni** [comment]
`B=small_subgroup_base` is the chosen smoothness and `small_subgroup_power` is the power of the `B`-smooth part in `r-1`. For example the `5`-smooth part in MNT4753 is `819200` and for MNT6753 is `671088640000=819200^2`

**Comment by Westlad** [comment]
Closed because completed.
